### ISSUE TITLE
フォント修正の件

### ISSUE THREAD

**Issue by clamm0363** [matanki-saito/ImperatorRomeJP#43]
[Hellenism-SemiBold.zip](https://github.com/matanki-saito/ImperatorRomeJP/files/4076774/Hellenism-SemiBold.zip)
同名のフォントファイルの差し替えをお願いいたします

**Comment by matanki-saito** [comment]
差し替え完了しました
https://github.com/matanki-saito/ImperatorRomeJP/commit/9c829a22e31167d5ec2ec4ac382e19a7662d7289
